### ISSUE TITLE
Not really tracking down each host usage

### ISSUE THREAD

**Issue by darrepac** [mstojek/nlbw2collectd#4]
While the global usage seems to be well tracked down:
![image](https://github.com/mstojek/nlbw2collectd/assets/7128994/29653b2c-ac60-4168-8410-b1c276bce33e)
The usage per host is nearly null like if a lot were missed...
![image](https://github.com/mstojek/nlbw2collectd/assets/7128994/2bbbe9b3-82d6-4d3a-9160-040c952ca01d)

**Comment by mstojek** [comment]
What about Nlbwmon, does it track traffic correctly? Please check it in Luci.

**Comment by mstojek** [comment]
Please check if nlbwmon is correctly counting statistics.  Login to Openwrt and go to: Luci->Bandwidth Monitor->Display 

We need to find if this is my script issue or Nlbwmon

**Comment by darrepac** [comment]
yes stats seems ok

![image](https://github.com/mstojek/nlbw2collectd/assets/7128994/87a4521d-178e-449b-b0e8-edb32d00882d)

**Comment by mstojek** [comment]
I need to think about what is happening and add some debugs so we can see  why there is no traffic recorded.

**Comment by mstojek** [comment]
If you still have this problem and want to check what is happening here you can use debug script: https://github.com/mstojek/nlbw2collectd/blob/main/debug/nlbw2collectd.lua
You just need to replace original "nlbw2collectd.lua" with the one stored in debug directory. 
Then we can check the debug logs with:
`# logread | grep collectd`
Please note that debug log will contain detailed info about your host names and their network usage. You may want to anonimyze this data before sending this for public view here.
Since this debug script will put lot of logs into Openwrt log use this script only for short period of time (like 5 minutes.)

**Comment by mstojek** [comment]
If problem still exist reopen this issue.
