### ISSUE TITLE
Incongruence in total data and timeframe

### ISSUE THREAD

**Issue by giuliomagnifico** [mstojek/nlbw2collectd#8]
Hi,
It's me again 😄

I'm trying to use the plugin with Prometheus, but I'm encountering a strange issue. The total data in a 5min timeframe is exceeding that of a 24h timeframe, and all the data seems a bit messed up.

See the screenshots:

![SCR-20240726-ndoi](https://github.com/user-attachments/assets/7fa44670-e030-4767-bab9-76362f92cc1f)
![SCR-20240726-ndqt](https://github.com/user-attachments/assets/d939dd3e-975c-4b75-a0df-12cc095fb5b2)

I'm also encountering the same problem on the LuCi graphs page. The data is inconsistent across different timeframes, i.e. the 1h timeframe shows more total data than the 1d.

Could this be related to my previous issues? -> https://github.com/mstojek/nlbw2collectd/issues/7

Thanks

**Comment by mstojek** [comment]
Could you please share the luci statistics data?

**Comment by giuliomagnifico** [comment]
Here you are. I noticed that the data appears to be correct after running it for several hours, so the issue might be only with Prometheus.

![SCR-20240726-pwqv](https://github.com/user-attachments/assets/6c4ec66a-ab6b-4a0d-8898-c9fc0f5a8793)

However Prometheus data are still inconsistent, probably your collectd plugin isn't working properly with it.

**Comment by mstojek** [comment]
Let me ask more questions. Do you export from collectd more data than my script delivers? E.g. try to export traffic data from ethernet interface of you router (like eth0, wan0 or wlan0). Is that data correct in Prometheus? Generally the data collected by my script (sum of the traffic from all hosts) shall be equal to the wan Total traffic.
Can you check if the data in collectd is equal to the data collected by nlbwmon itself  in Luci. Comparing might be tricky since you can not choose collection period in Nlbwmon.
If the collectd data is correct probably my script is ok and this is rather collectd->prometheus issue.
One thing that might be problematic in my script is the 32 bit counter workaround (see https://github.com/mstojek/nlbw2collectd/issues/7#issuecomment-2198599556). You may want to remove this workaround and check the results.

**Comment by giuliomagnifico** [comment]
I enabled the collectd Netlink plugin on the WAN interface and removed the 32-bit counter workaround, but the data appears to be still inconsistent:

For the same 1 hour timeframe:

![SCR-20240727-minu](https://github.com/user-attachments/assets/c84d8a93-da03-4a83-8129-2f7477c50641)

![SCR-20240727-misw](https://github.com/user-attachments/assets/f49186fc-07a8-46dc-8c4d-01d424f04848)

Isn't the RX WAN show 655MB, while Nlbwmon shows only a few MB (around 20MB)?

**Comment by mstojek** [comment]
Ok, so wee need to do some debugging here to determine what is wrong.
What I propose is as follows:
1. Note the current 1 hour traffic usage for your laptop in:
- Nlbwmon (Luci->Services->Bandwidth Monitor)
- Collectd (Luci->Statistics->Graphs->Firewall)
- Prometheus
2. Note the current 1 hour Wan interface usage in 
- (Luci->Statistics......)
- Prometheus
3. Download 1GB file from the internet to the laptop
4. Wait 3-5 minutes for the statistic to refresh
5. Note the current 1 hour traffic usage for your laptop in:
- Nlbwmon (Luci->Services->Bandwidth Monitor)
- Collectd (Luci->Statistics->Graphs->Firewall)
- Prometheus
6. Note the current 1hour Wan interface usage in 
- (Luci->Statistics......)
- Prometheus
7. Check whether WAN and laptop statistics increased for about 1GB. Inform me where it did not happened
8. Enable the 32bit workaround that you disabled
9. Repeat steps 1-6
10.  Check whether WAN and laptop statistics increased for about 1GB. Inform me where it did not happened

With this data we can narrow down what is the source of the problem and where the statistics are missing.
One more thing - what Openwrt version are you using.
Last thing: for Nlbwmon proper work you may want to increase Nlbwmon buffers, see: [link](https://forum.openwrt.org/t/nlbwmon-hangs-after-few-days-of-use/138788/63)

```
cat /etc/config/nlbwmon

config nlbwmon
        option netlink_buffer_size '1048576'

cat /etc/sysctl.d/12-nlbwmon.conf

net.core.rmem_default=1048576
net.core.wmem_default=1048576
net.core.rmem_max=1048576
net.core.wmem_max=1048576
```

**Comment by giuliomagnifico** [comment]
Wow, thanks for the exhaustive reply.

I've done better, I simply stopped collectd, deleted 
iptables-mangle-nlbwmon_tx
iptables-mangle-nlbwmon_rx

**Comment by giuliomagnifico** [comment]
Wow, thanks for the exhaustive reply. 

About the nlbwmon buffer, I had already increased it (years ago) because I was aware of that issue: 

```
config nlbwmon
	option netlink_buffer_size '212992'
	option commit_interval '10m'
	option refresh_interval '30s'
	option database_interval '1'
	option protocol_database '/usr/share/nlbwmon/protocols'
	option database_generations '0'
	option database_limit '0'
	option database_directory '/mnt/sda1/nlbwmon'
	option database_prealloc '1'
	list local_network '192.168.0.0/16'
	list local_network '172.16.0.0/12'
	list local_network '10.0.0.0/8'
	list local_network '192.168.1.1/24'
	list local_network '192.168.2.1/24'
	list local_network '10.4.0.1/32'
	list local_network 'wan'
	list local_network 'wg0'
```


About the incongruent data,  I did better: I simply stopped collectd and deleted the folders

```
iptables-mangle-nlbwmon_tx
iptables-mangle-nlbwmon_rx
netlink-pppoe-wan
```

Then I restarted collectd, I downloaded 1.17Gb of Arch Linux ISO from my Mac Mini and here are the differences:

![SCR-20240727-ssfx](https://github.com/user-attachments/assets/614cfbf7-9249-41e0-b867-8fb12ee5ba75)

![SCR-20240727-suxs](https://github.com/user-attachments/assets/fff52cef-9d5e-4f2d-9103-957ce696ab95)

Netlink reports the correct data, nlbwmon isn't correct.

I also checked the (slightly different) _prometheus-node-exporter-lua-nat_traffic_ and it's quite accurate (it reports higher value because I checked 10 min after the download):


![SCR-20240727-syzm](https://github.com/user-attachments/assets/2ea06fb0-95b5-4672-a7c4-cf0eccd95d55)

**Comment by mstojek** [comment]
What about Nlbwmon statistics (Luci->Services->Bandwidth Monitor) are threy correct?

**Comment by giuliomagnifico** [comment]
I don't have the hourly timeframa but only monthly but they look correct, if you know how to set different timeframes in LuCi I can see better.

![SCR-20240728-irhn](https://github.com/user-attachments/assets/4251c9b1-44a3-427a-96c2-61f9038f68cb)

**Comment by mstojek** [comment]
It is very simple :), you take a sheet of paper, note on  paper your current nlbwmon usage for laptop, Download 1GB of data, after 5 minutes you  note current laptop usage, substract one value from another and you have detailed usage.
Please exeute steps from 1 to 10 from my [previous note](https://github.com/mstojek/nlbw2collectd/issues/8#issuecomment-2254170441) and give me details. Please note that I also asked for results with 32bit workaround and without. Unforunatelly all those details are required to determine where the problem is. It could be 32bit workaround issue, nlbwmon issue, my script, issue collectd issue or prometheus issue.

**Comment by mstojek** [comment]
Looking into the data you already provided you should execute test with my script code containing 32 bit workaround:
```
    local tx_bytes_modulo = tx_bytes % 2147483647 --workaround since we can not report to collectd more than 32bit integer
    local rx_bytes_modulo = rx_bytes % 2147483647 --workaround since we can not report to collectd more than 32bit integer
```

I suspect that removing the modulo part `% 2147483647` causes problems with collectd data (Luci->Statistics->Graphs->Firewall).

I have no idea why the collectd data was incorrect  (Luci->Statistics->Graphs->Firewall) and the prometheus data was correct ( prometheus-node-exporter-lua-nat_traffic) in https://github.com/mstojek/nlbw2collectd/issues/8#issuecomment-2254239024

Getting the data from https://github.com/mstojek/nlbw2collectd/issues/8#issuecomment-2254170441  will help to understand where the problem is

**Comment by giuliomagnifico** [comment]
Okay, I stopped all the services, deleted all the folders of Nlbwmon (renamed as nlbwmon_old), and your plugin (iptables-mangle-nlbwmon_tx, iptables-mangle-nlbwmon_rx, netlink-pppoe-WAN).


```
root@R4S:~# /etc/init.d/nlbwmon stop
root@R4S:~# /etc/init.d/collectd stop
root@R4S:~# ls -l /mnt/sda1/
-rw-r-----    1 root     root          4507 Jun  1  2022 20220501.db.gz
-rw-r-----    1 root     root          4444 Jul  1  2022 20220601.db.gz
-rw-r-----    1 root     root          4053 Aug  1  2022 20220701.db.gz
-rw-r-----    1 root     root           941 Aug  1  2022 20220801.db.gz
drwxr-xr-x    3 root     root          4096 Jul  2 13:22 R4S
drwxr-xr-x    2 root     root          4096 Jul  1 05:55 nlbwmon_old
root@R4S:~# /etc/init.d/nlbwmon start
root@R4S:~# /etc/init.d/collectd start
root@R4S:~# /etc/init.d/nlbwmon status
running
root@R4S:~# /etc/init.d/collectd status
running
root@R4S:~# 
```

This is without the modulo part % 2147483647, as with it, I’ve already done the test.

After checking all the data, here are the differences:

![SCR-20240728-mekn](https://github.com/user-attachments/assets/e41014e4-5d34-4f80-8363-95d30a43fa4b)

![SCR-20240728-meft](https://github.com/user-attachments/assets/c7b71a06-eb12-4dc9-a7fb-d2f37d014e33)

<img width="952" alt="SCR-20240728-mfzn" src="https://github.com/user-attachments/assets/68c7150e-64ac-4fb1-ab3e-b390e3ff157d">

Now the discrepancies look even bigger.

Other info:

I'm running on OpenWrt 23.05.4 r24012 with the nlbwmon and collectd data saved to an external usb3 drive.

Here are my firewall config if can help (I haven't enabled ipv6, only ipv4):

```
root@R4S:~# cat /etc/config/firewall 

config defaults
	option input 'ACCEPT'
	option output 'ACCEPT'
	option forward 'REJECT'
	option synflood_protect '1'

config zone
	option name 'lan'
	option input 'ACCEPT'
	option output 'ACCEPT'
	option forward 'ACCEPT'
	list network 'lan'
	list network 'wg0'

config zone
	option name 'wan'
	option output 'ACCEPT'
	option masq '1'
	option mtu_fix '1'
	option input 'DROP'
	option forward 'DROP'
	list network 'wan'
	list network 'wan6'
	list network 'modem'

config forwarding
	option src 'lan'
	option dest 'wan'

config rule
	option name 'Allow-DHCP-Renew'
	option src 'wan'
	option proto 'udp'
	option dest_port '68'
	option target 'ACCEPT'
	option family 'ipv4'

config rule
	option name 'Allow-Ping'
	option src 'wan'
	option proto 'icmp'
	option icmp_type 'echo-request'
	option family 'ipv4'
	option target 'ACCEPT'

config rule
	option name 'Allow-IGMP'
	option src 'wan'
	option proto 'igmp'
	option family 'ipv4'
	option target 'ACCEPT'

config rule
	option name 'Allow-DHCPv6'
	option src 'wan'
	option proto 'udp'
	option dest_port '546'
	option family 'ipv6'
	option target 'ACCEPT'
	option enabled '0'

config rule
	option name 'Allow-ICMPv6-Input'
	option src 'wan'
	option proto 'icmp'
	list icmp_type 'echo-request'
	list icmp_type 'echo-reply'
	list icmp_type 'destination-unreachable'
	list icmp_type 'packet-too-big'
	list icmp_type 'time-exceeded'
	list icmp_type 'bad-header'
	list icmp_type 'unknown-header-type'
	list icmp_type 'router-solicitation'
	list icmp_type 'neighbour-solicitation'
	list icmp_type 'router-advertisement'
	list icmp_type 'neighbour-advertisement'
	option limit '1000/sec'
	option family 'ipv6'
	option target 'ACCEPT'
	option enabled '0'

config rule
	option name 'Allow-MLD'
	option src 'wan'
	option proto 'icmp'
	option src_ip 'fe80::/10'
	list icmp_type '130/0'
	list icmp_type '131/0'
	list icmp_type '132/0'
	list icmp_type '143/0'
	option family 'ipv6'
	option target 'ACCEPT'

config rule
	option name 'Allow-ICMPv6-Forward'
	option src 'wan'
	option dest '*'
	option proto 'icmp'
	list icmp_type 'echo-request'
	list icmp_type 'echo-reply'
	list icmp_type 'destination-unreachable'
	list icmp_type 'packet-too-big'
	list icmp_type 'time-exceeded'
	list icmp_type 'bad-header'
	list icmp_type 'unknown-header-type'
	option limit '1000/sec'
	option family 'ipv6'
	option target 'ACCEPT'
	option enabled '0'

config rule
	option name 'Allow-IPSec-ESP'
	option src 'wan'
	option dest 'lan'
	option proto 'esp'
	option target 'ACCEPT'

config rule
	option name 'Allow-ISAKMP'
	option src 'wan'
	option dest 'lan'
	option dest_port '500'
	option proto 'udp'
	option target 'ACCEPT'

config rule
	option name 'WireGuard'
	list proto 'udp'
	option src 'wan'
	option dest_port '51820'
	option target 'ACCEPT'

config zone
	option name 'iot'
	option output 'ACCEPT'
	list network 'iot'
	option forward 'DROP'
	option input 'DROP'

config zone
	option name 'guest'
	option output 'ACCEPT'
	list network 'guest'
	option input 'DROP'
	option forward 'DROP'

config rule
	option name 'Guest DHCP'
	list proto 'udp'
	option src 'guest'
	option dest_port '67-68'
	option target 'ACCEPT'

config rule
	option name 'Guest DNS'
	option src 'guest'
	option dest_port '53'
	option target 'ACCEPT'
	option dest 'lan'

config forwarding
	option src 'lan'
	option dest 'guest'

config forwarding
	option src 'lan'
	option dest 'iot'

config rule
	option name 'IoT DHCP'
	list proto 'udp'
	option src 'iot'
	option dest_port '67-68'
	option target 'ACCEPT'

config rule
	option name 'IoT DNS'
	option src 'iot'
	option dest_port '53'
	option target 'ACCEPT'
	option dest 'lan'

config rule
	option name 'IoT mDNS'
	list proto 'udp'
	option src 'iot'
	list dest_ip '224.0.0.251'
	option dest_port '5353'
	option target 'ACCEPT'

config forwarding
	option src 'guest'
	option dest 'wan'

config rule
	option src 'guest'
	list dest_ip '192.168.2.0/24'
	option target 'DROP'
	option dest 'wan'
	option name 'Guest Modem '
	list proto 'all'

config rule
	option src 'iot'
	list dest_ip '192.168.2.0/24'
	option target 'DROP'
	option name 'IoT Modem'
	list proto 'all'
	option dest 'wan'

config forwarding
	option src 'iot'
	option dest 'wan'

config rule
	option name 'IPad kiosk to LAN'
	option src 'iot'
	list src_ip '192.168.50.194'
	option target 'ACCEPT'
	option dest 'lan'

root@R4S:~# 
```

**Comment by mstojek** [comment]
ok, I believe that the issue is that you compare nlbwmon upload with collectd download. 
Nlbwmon upload is collectd rx_hostname. Tell me what is Nlbwmon Upload for iPad-Kiosk and collectd tx_iPad-Kiosk.

**Comment by giuliomagnifico** [comment]
I don't understand this. Are the rx and tx reversed in your plugin? Netlink also reports downloaded bytes as rx.

You can see the upload data for the iPad-kiosk in Nlbwmon (1.68 MiB) in the screenshot above. 

And here's your plugin tx data, that is also incorrect.

![SCR-20240728-mqlv](https://github.com/user-attachments/assets/889db5f7-3e27-4f08-a8da-7937d8bcf5cc)

**Comment by mstojek** [comment]
You showed in collectd stat that between 13:11 and 13:15 iPad-kiosk used 55,8MB, what was the Nlbwmon usage between 13:11 and 13:15? 
When looking into transfer RX on pppoe-wan we see that at 13:11 the speed was about 375 kb/s similar to what we see for tx_iPad-Kiosk is showing.
Regarding the tx/rx thing: I used what [Iptmon](https://github.com/oofnikj/iptmon) has been using. I agree that this is reverse logic - the explanation was that this is from router point of view, not client point of view.

**Comment by giuliomagnifico** [comment]
Oh about the reverse rx and tx nice to know, I’ve always wrong. Thanks!

About the usage, as I said, I deleted both/all the folders of both Nlbwmon in LuCi and the two folders of your script, then I restarted both the services (collect and nlbwmon) so both the data should be the same. 

From 13:00 to 13:15 the data used by iPad-kiosk are 416mb from nlbwmon in LuCi and 55.8Mb from your script (if is the tx data, see the post above https://github.com/mstojek/nlbw2collectd/issues/8#issuecomment-2254498833)

Both of these screenshots are taken after I deleted all the folders with the usage data (nlbwmon folder and your iptables-mangle-nlbwmon_* folders). Then restarted both the services. 


![image](https://github.com/user-attachments/assets/f62ad05c-aa8b-459c-a6a9-e85f95a9e6af)

![image](https://github.com/user-attachments/assets/a9005d6a-a711-48f7-b51e-f558c2305e89)

**Comment by mstojek** [comment]
In this picture ![picture](https://github.com/user-attachments/assets/c52d029c-89ba-4fa2-9850-6acb47e21f35)
 I can see that your system used between 12:56 and 13:15 - 429 MB.

In this picture ![picture](https://github.com/user-attachments/assets/f14a66ab-91a3-4075-a4e2-1ecd0c0a63cc) we can see that between 13:11:30 and 13:15 iPad-kiosk used 55MB (note that this picture has 1 hour timespan starting at 13:11:30 ending at 14:11:30 while all other collcetd pictures are starting earlier). 

Nlbwmon states below
![obraz](https://github.com/user-attachments/assets/cfed1e64-2f86-4fc0-9c25-9302037cd7ca)
 that iPad-kiosk used 416,64MB - but is this since 13:11:30 or since 12:56? The picture suggest that this is since 12:56 (416,64 MB is consictent with total usage 429MB). If that is the case (and I can be wrong) you are comparing counter starting form 12:56 with counter starting from 13:11. Am I right?

**Comment by giuliomagnifico** [comment]
The timeframes are identical. I deleted all the data in every folder and restarted the collectors. I only took the screenshot a few minutes later, so you won’t see any time before 13:11 in the second screenshot.

**Comment by mstojek** [comment]
I edited my [response](https://github.com/mstojek/nlbw2collectd/issues/8#issuecomment-2254585120) just moment ago, please read it again - sorry for this edit. 
Almost all your pictures start at 12:14 with exception of the collectd tx data that show 55 MB and starts at 13:11 and this is because you choose 1 hour timespan and took the picture at 14:11. So we losed the information what was collected beetween 12:45 and 13:11. This has nothing to do with my script, thios is just wrong time line. You need to collect all data at the same time. If you chose different start time you will get different results

**Comment by giuliomagnifico** [comment]
I ran the test again.

First, I deleted all the folders at 10:00. Then, I checked the last hour's data at 13:05.

```
 OpenWrt 23.05.4, r24012-d8dd03c46f
 -----------------------------------------------------
root@R4S:~# /etc/init.d/nlbwmon stop
root@R4S:~# /etc/init.d/collectd stop
root@R4S:~# rm -rf /mnt/sda1/R4S/R4S/iptables-mangle-nlbwmon_*
root@R4S:~# rm -rf /mnt/sda1/R4S/R4S/netlink-pppoe-wan/
root@R4S:~# cd /mnt/sda1/
root@R4S:/mnt/sda1# ls
20220501.db.gz  20220601.db.gz  20220701.db.gz  20220801.db.gz  R4S             nlbwmon
root@R4S:/mnt/sda1# mv nlbwmon/ nlbwmon_old/
root@R4S:/mnt/sda1# ls
20220501.db.gz  20220601.db.gz  20220701.db.gz  20220801.db.gz  R4S             nlbwmon_old
root@R4S:/mnt/sda1# /etc/init.d/collectd start
root@R4S:/mnt/sda1# /etc/init.d/nlbwmon  start
root@R4S:/mnt/sda1# /etc/init.d/nlbwmon  status
running
root@R4S:/mnt/sda1# /etc/init.d/collectd   status
running
root@R4S:/mnt/sda1# 
```

![SCR-20240730-lrrl](https://github.com/user-attachments/assets/aea055e8-a06e-4e91-82f4-4694f994f9e4)
![SCR-20240730-lrzt jpg](https://github.com/user-attachments/assets/494fd0fb-6988-47c6-80d0-91ef3c355783)
![SCR-20240730-luue](https://github.com/user-attachments/assets/7394dca9-b1e9-456d-99bb-9295e9d8dcea)

I'm not sure if I misunderstood something, but the numbers don't seem correct to me.

**Comment by mstojek** [comment]
Yes, you are comparing count of packets in Collectd with count of traffic in Prometheus..... Please tkae the screenshot from traffic data from Collectd not Packet count data.

Can you confirm that now the Nlbwmon data and Collectd data is correct?
Because now it seems that the last issue that we have is export from Collectd to Prometheus - is that right?

Are you able to create chart in Prometheus that shows also the pppoe-wan traffic so we can compare the wan traffic in collectd with wan traffci in Prometheus. I am asking for this since those are similar charts and data. If we are able to export wan data to Prometheus we should be able to export Nlbwmon data to Prometheus also.

**Comment by giuliomagnifico** [comment]
Oh, what a stupid I'm, sorry, I took the wrong chart screenshot. I'll try again with the bytes instead of packets.

And I'll try also to generate the chart in Prometheus!

**Comment by giuliomagnifico** [comment]
I ran the test again by deleting all the folders and then watching a movie. After 2-3 hours, here are the results of the last 1 hour (I hope that this time I haven't made silly mistakes):

![SCR-20240730-swbv](https://github.com/user-attachments/assets/f767f8c0-4e7e-4315-b4fd-58a36559a3e8)

![mangle-nlbwon_tx](https://github.com/user-attachments/assets/0edb1760-887e-48da-a034-408737cbc98b)
![mangle-nlbwmon_rx](https://github.com/user-attachments/assets/7f7a006f-dea0-4a35-a8cc-541e10aa3493)
![SCR-20240730-swyw](https://github.com/user-attachments/assets/d0e2c0e4-31b2-420d-9ab2-76b828c26be6)

![SCR-20240730-sxwc](https://github.com/user-attachments/assets/955ba524-e7d9-4ee9-9da4-df5e9e7807de)

**Comment by mstojek** [comment]
What is the total usage for problematic hosts in Nlbwmon? Especially I am interested what is the AppleTv usage in Nlbwmon (Luci->Services->Bandwidth Monitor)

**Comment by mstojek** [comment]
I think we have several problems here, we need to clean up all of them one by one....

1. We need to check if the workaround exist in my script, lack of workaround casues problems probably. Check if you have following lines in my [nlbw2collectd.lua](https://github.com/mstojek/nlbw2collectd/blob/main/nlbw2collectd.lua):
    ```
    local tx_bytes_modulo = tx_bytes % 2147483647 --workaround since we can not report to collectd more than 32bit integer
    local rx_bytes_modulo = rx_bytes % 2147483647 --workaround since we can not report to collectd more than 32bit integer
    ```

    **Please change this line befor proceeding any tests.**

2. I still have no idea whether the problem is within Nlbwmon (Luci->Services->Bandwidth Monitor) or
Collectd (Luci->Statistics->Graphs->Firewall). Are you able to compare those statistics and confirm if any of them is providing proper results? 
    The flow of usage data is as follows: Nlbwmon->My script->Collectd->Prometheus. We need to determine where the problem starts. Now I know that Collectd data are incorrect, but I have no idea whether the reason is my script or Nlbwmon itself

3. For sure there is problem with exporting Collectd data to Prometheus. Take a look at the picture below - the Prometheus picture is incorrect (although the total data seems more/less good)

   ![obraz](https://github.com/user-attachments/assets/eec0d3cd-c1c9-4264-b18d-8d0fd2923820)
   ![obraz](https://github.com/user-attachments/assets/a61eecf7-b909-4f82-bb48-6aab2a761590)

   The Prometheus WAN speed is constant line while Collectd properly shows current line speed.
   Are you able to fix this?
   I am asking you to provide proper WAN statistics in Prometheus because it will help us to provide proper "per host" statistics later.

4. Why Prometheus shows 'Total' usage for 192.168.1.7 in GB/s - this does not make any sense. Total usage should be in GB or MB, but not the MB/s

**Comment by giuliomagnifico** [comment]
Okay, I ran the test again, deleted all the folders at 12:50, restarted the services, and checked the data at 13:40. The data now appear correct.

<img width="968" alt="SCR-20240731-mduc" src="https://github.com/user-attachments/assets/142f296b-9e84-4eca-918f-32e9b8f920f1">
<img width="951" alt="SCR-20240731-mcqx" src="https://github.com/user-attachments/assets/15964a22-282c-4017-89a4-2530f0dfd42e">
<img width="945" alt="SCR-20240731-mcxc" src="https://github.com/user-attachments/assets/621d6907-b7c1-4dd2-8489-1a0d3df3bb10">

![SCR-20240731-megc](https://github.com/user-attachments/assets/65b44f94-7fe2-4c01-8fa7-cc4b64cdede5)





But, is it normal for Prometheus to show the same amount of data for different timeframes? Maybe this is the issue causing my confusion!

<img width="816" alt="20240731-134040" src="https://github.com/user-attachments/assets/67da9dcc-7e44-4dc7-9668-c27c93bdca0f">

**Comment by mstojek** [comment]
Definitely the Prometheus data is incorrect. Unfortunatelly I do not know Prometheus well enough to help you were the problem is. I think you need to google how to export Collectd data to Prometheus. I think you show similar problem for WAN traffic data in prometheus (in picture below).

![image](https://github.com/user-attachments/assets/4d852591-b496-4b26-af2a-c1f7e4bee785)


 Maybe you want to switch to InfluxDB an Grafana? I have such working setup.

**Comment by giuliomagnifico** [comment]
Don't worry, and thanks a lot for all your help!

I also can't understand what's going on with Prometheus. I have lots of other collectd exporters (ping, temperatures, CPU usage, etc.) and all are working well. However, I'm not using the collectd WAN metrics because it exports only the WAN errors (collisions, drops, errors, etc.).

Here's the full output of the collectd-exporter for Prometheus: [https://pastebin.com/Hnhj696q](https://pastebin.com/Hnhj696q)

I have a very big dashboard for my setup, but in the end, I will use the normal Prometheus node-exporter exporters. They also have lots of useful info, but your script is very handy because it automatically translates the IPs to hostnames and reports the overall traffic. Instead, the Prometheus node-exporter exports the data for every external IP that is requested:

![SCR-20240801-iyuu](https://github.com/user-attachments/assets/eeda6f7f-7376-485e-9a47-fd9659d275f6)

And here's the full dashboard: https://i.imgur.com/pUvUvqf.jpeg

PS: I have written [on my blog](https://giuliomagnifico.blog/post/2024-07-08-home-setup-v5/) how I've built the Grafana dashboards, maybe something (like other exporters) is creating issue with your script. I'll try to investigate, first time I see this issue. But I will not add another DB (InfluxDB) only for this stat 😄 (I have already 3/4 DB on my Prometheus-Grafana server).

Thanks again.

**Comment by mstojek** [comment]
Your Grafana Dashbaoard (and all setup) is pretty impressive. Awesome job!
I fully understand why you do not want to add any new database here. 
I am pretty sure that there is a solution for the NLBwmon data export to Prometheus but I have no idea where the problem could be. I took look at collectd-exporter for Prometheus: https://pastebin.com/Hnhj696q and verified if it uses proper data types and it is ok (I use "ipt_bytes" that translate to "value:DERIVE"). 
Good luck with your setup!

**Comment by mstojek** [comment]
Your Grafana Dashbaoard (and all setup) is pretty impressive. Awesome job!
I fully understand why you do not want to add any new database here. 
I am pretty sure that there is a solution for the NLBwmon data export to Prometheus but I have no idea where the problem could be. I took look at collectd-exporter for Prometheus: https://pastebin.com/Hnhj696q and verified if it uses proper data types and it is ok (I use "ipt_bytes" that translate to "value:DERIVE"). 
Good luck with your setup!

**Comment by giuliomagnifico** [comment]
Thank you. I'll try to check out the collectd exporter for Prometheus if I'm able to understand something. 

It's really strange but could just be a bug in Grafana. Because the data in Prometheus metrics is finee, but 'shit happen' when I try change the timeframes.

That's why I initially thought your exporter was the problem, but I was wrong.

**Comment by lirener** [comment]
dalao 牛逼！
